language: java
os: linux
dist: bionic
branches:
  only: 
    - master
 cache:
   directories:
     - $HOME/.m2
 env:
   global: 
     - M2_HMOME=/usr/local/maven
     
 before_install:
   - export: M2_HOME=/usr/share/maven
 install: true
 script:
   - mvn clean install
